"""
evidence.py

Guards against fabricated statistics. The LLM is instructed (see prompts.py)
to never invent numeric claims -- but instructions alone are not enough, so
this module enforces it in code:

1. Every `Statistic` must carry a non-empty `source`.
2. Statistics without a source are dropped (never silently "fixed" by
   inventing a source).
3. Optionally, an application-maintained allowlist of pre-verified stats can
   be used to check that a claimed value matches a known-good figure.

This keeps "real data or nothing" as a hard invariant rather than a prompt-only
suggestion.
"""

from typing import List, Optional
from models import Statistic

# Example of a small, application-curated allowlist of verified statistics.
# In production this would be sourced from an internal, audited data table
# (e.g. IRDAI annual reports, company research) -- NOT generated by the LLM.
VERIFIED_STATISTICS_LIBRARY = {
    "health_insurance_penetration": Statistic(
        value="~4%",
        description="Health insurance penetration in India relative to GDP remains low compared to global peers.",
        source="IRDAI Annual Report",
        source_url="https://irdai.gov.in",
    ),
    "cashless_hospital_network": Statistic(
        value="10,000+",
        description="Typical scale of a large Indian insurer's cashless hospital network.",
        source="Industry publications (illustrative figure -- verify against insurer's current network before use)",
        source_url=None,
    ),
}


def filter_verified_statistics(statistics: Optional[List[Statistic]]) -> List[Statistic]:
    """
    Removes any statistic that does not carry a source. This is the
    enforcement point that prevents fabricated numbers from ever reaching
    a rendered email, regardless of what the LLM returned.
    """
    if not statistics:
        return []
    verified = []
    for stat in statistics:
        if stat.source and stat.source.strip():
            verified.append(stat)
    return verified


def get_verified_statistic(key: str) -> Optional[Statistic]:
    """Look up a pre-approved statistic by key from the curated library."""
    return VERIFIED_STATISTICS_LIBRARY.get(key)


def qualitative_fallback(topic: str) -> str:
    """
    A safe, non-numeric fallback statement to use when no verified statistic
    is available for a claim the campaign wants to make.
    """
    return f"Growing numbers of customers are turning to solutions like this for {topic.lower()}."
